src/main/java/org/ifbma/legacy/despot/entities/Workorder.java
package org.ifbma.legacy.despot.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.*;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

@Entity
@XmlRootElement
@Cacheable(false)
@NamedQueries({
    @NamedQuery(name = "Workorder.findAll", query = "SELECT w FROM Workorder w"),
    @NamedQuery(name = "Workorder.findById", query = "SELECT w FROM Workorder w WHERE w.id = :id"),
    @NamedQuery(name = "Workorder.findByDat", query = "SELECT w FROM Workorder w WHERE w.dat = :dat"),
    @NamedQuery(name = "Workorder.findByUhr", query = "SELECT w FROM Workorder w WHERE w.uhr = :uhr"),
    @NamedQuery(name = "Workorder.findByVon", query = "SELECT w FROM Workorder w WHERE w.von = :von"),
    @NamedQuery(name = "Workorder.findByUeber", query = "SELECT w FROM Workorder w WHERE w.ueber = :ueber"),
    @NamedQuery(name = "Workorder.findByNach", query = "SELECT w FROM Workorder w WHERE w.nach = :nach"),
    @NamedQuery(name = "Workorder.findByJob", query = "SELECT w FROM Workorder w WHERE w.job = :job"),
    @NamedQuery(name = "Workorder.findByFahrschecknr", query = "SELECT w FROM Workorder w WHERE w.fahrschecknr = :fahrschecknr"),
    @NamedQuery(name = "Workorder.findByPreis", query = "SELECT w FROM Workorder w WHERE w.preis = :preis"),
    @NamedQuery(name = "Workorder.findByFahrernr", query = "SELECT w FROM Workorder w WHERE w.fahrernr = :fahrernr"),
    @NamedQuery(name = "Workorder.findByTyp", query = "SELECT w FROM Workorder w WHERE w.typ = :typ"),
    @NamedQuery(name = "Workorder.findByPreischeck", query = "SELECT w FROM Workorder w WHERE w.preischeck = :preischeck"),
    @NamedQuery(name = "Workorder.findByFahrscheckcheck", query = "SELECT w FROM Workorder w WHERE w.fahrscheckcheck = :fahrscheckcheck"),
    @NamedQuery(name = "Workorder.findBySonderkonditionen", query = "SELECT w FROM Workorder w WHERE w.sonderkonditionen = :sonderkonditionen"),
    @NamedQuery(name = "Workorder.findBySumme", query = "SELECT w FROM Workorder w WHERE w.summe = :summe"),
    @NamedQuery(name = "Workorder.findByKuerzel", query = "SELECT w FROM Workorder w WHERE w.kuerzel = :kuerzel"),
    @NamedQuery(name = "Workorder.findByFirmierung1", query = "SELECT w FROM Workorder w WHERE w.firmierung1 = :firmierung1")})
public class Workorder implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Column(precision = 17, scale = 17)
    private Double dat;
    @Size(max = 20)
    @Column(length = 20)
    private String uhr;
    @Size(max = 50)
    @Column(length = 50)
    private String von;
    @Size(max = 50)
    @Column(length = 50)
    private String ueber;
    @Size(max = 50)
    @Column(length = 50)
    private String nach;
    @Size(max = 50)
    @Column(length = 50)
    private String job;
    @Size(max = 50)
    @Column(length = 50)
    private String fahrschecknr;
    private BigDecimal preis;
    private Integer fahrernr;
    @Size(max = 50)
    @Column(length = 50)
    private String typ;
    @Size(max = 50)
    @Column(length = 50)
    private String preischeck;
    @Size(max = 50)
    @Column(length = 50)
    private String fahrscheckcheck;
    private Integer sonderkonditionen;
    private BigDecimal summe;
    private String kuerzel;
    @Size(max = 254)
    @Column(length = 254)
    private String firmierung1;

    @Transient
    private Boolean undispatched;

    public Workorder() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Double getDat() {
        return dat;
    }

    public void setDat(Double dat) {
        this.dat = dat;
    }

    public String getUhr() {
        return uhr;
    }

    public void setUhr(String uhr) {
        this.uhr = uhr;
    }

    public String getVon() {
        return von;
    }

    public void setVon(String von) {
        this.von = von;
    }

    public String getUeber() {
        return ueber;
    }

    public void setUeber(String ueber) {
        this.ueber = ueber;
    }

    public String getNach() {
        return nach;
    }

    public void setNach(String nach) {
        this.nach = nach;
    }

    public String getJob() {
        return job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public String getFahrschecknr() {
        return fahrschecknr;
    }

    public void setFahrschecknr(String fahrschecknr) {
        this.fahrschecknr = fahrschecknr;
    }

    public BigDecimal getPreis() {
        return preis;
    }

    public void setPreis(BigDecimal preis) {
        this.preis = preis;
    }

    public Integer getFahrernr() {
        return fahrernr;
    }

    public void setFahrernr(Integer fahrernr) {
        this.fahrernr = fahrernr;
    }

    public String getTyp() {
        return typ;
    }

    public void setTyp(String typ) {
        this.typ = typ;
    }

    public String getPreischeck() {
        return preischeck;
    }

    public void setPreischeck(String preischeck) {
        this.preischeck = preischeck;
    }

    public String getFahrscheckcheck() {
        return fahrscheckcheck;
    }

    public void setFahrscheckcheck(String fahrscheckcheck) {
        this.fahrscheckcheck = fahrscheckcheck;
    }

    public Integer getSonderkonditionen() {
        return sonderkonditionen;
    }

    public void setSonderkonditionen(Integer sonderkonditionen) {
        this.sonderkonditionen = sonderkonditionen;
    }

    public BigDecimal getSumme() {
        return summe;
    }

    public void setSumme(BigDecimal summe) {
        this.summe = summe;
    }

    public String getKuerzel() {
        return kuerzel;
    }

    public void setKuerzel(String kuerzel) {
        this.kuerzel = kuerzel;
    }

    public String getFirmierung1() {
        return firmierung1;
    }

    public void setFirmierung1(String firmierung1) {
        this.firmierung1 = firmierung1;
    }

    public Boolean isUndispatched() {
        if (fahrernr == null) {
            undispatched = Boolean.TRUE;
        } else if (fahrernr.intValue() <= 1) {
            undispatched = Boolean.TRUE;
        } else {
            undispatched = Boolean.FALSE;
        }
        return undispatched;
    }

    public void setUndispatched(Boolean open) {
        this.undispatched = open;
        this.fahrernr = 0;
    }

}

src/main/java/org/ifbma/legacy/despot/jsf/WorkorderController.java
package org.ifbma.legacy.despot.jsf;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.inject.Named;
import org.ifbma.legacy.despot.entities.Workorder;
import org.ifbma.legacy.despot.jsf.util.JsfUtil;
import org.ifbma.legacy.despot.jsf.util.PaginationHelper;
import org.ifbma.legacy.despot.jsfbeans.WorkorderFacade;

@Named("workorderController")
@SessionScoped
public class WorkorderController implements Serializable {

    static int PAGE_SIZE = 10;

    private Workorder current;
    private DataModel items = null;
    @EJB
    WorkorderFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public WorkorderController() {
    }

    public Workorder getSelected() {
        if (current == null) {
            current = new Workorder();
            selectedItemIndex = -1;
        }
        return current;
    }

    @PostConstruct
    public void initialize() {
        int pageSize = Integer.parseInt(ResourceBundle.getBundle("/Bundle")
                .getString("Workorder_Pagesize"));
        if (pageSize > 0) {
            PAGE_SIZE = pageSize;
        }
    }

    private WorkorderFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(PAGE_SIZE) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(
                            new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Workorder) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Workorder();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle")
                    .getString("WorkorderCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle")
                    .getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Workorder) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle")
                    .getString("WorkorderUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle")
                    .getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Workorder) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle")
                    .getString("WorkorderDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle")
                    .getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(
                    new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    /**
     * Return items as List, as c:forEach can not cope with DataModel and all
     * the other collection tags can not build pm:view.
     * <p/>
     * As the List should correspond to DataModel, it has to follow the
     * rebuilding pattern. So it calls getItems resulting in the query being
     * put on the em twice.
     * @return
     */
    public List<Workorder> getItemsAsList() {
        getItems();
        int start = getPagination().getPageFirstItem();
        int end = getPagination().getPageFirstItem() + getPagination().getPageSize();
        return getFacade().findRange(new int[]{start, end});
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    public void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = Workorder.class)
    public static class WorkorderControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            WorkorderController controller = (WorkorderController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "workorderController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Workorder) {
                Workorder o = (Workorder) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object
                        + " is of type " + object.getClass().getName()
                        + "; expected type: " + Workorder.class.getName());
            }
        }

    }

}

src/main/java/org/ifbma/legacy/despot/jsfbeans/LoginBean.java
package org.ifbma.legacy.despot.jsfbeans;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

@Named
@RequestScoped
public class LoginBean {

    private String username;
    private String password;

    public LoginBean() {
    }

    public String login() {
        FacesContext context = getContext();
        HttpServletRequest request = getRequest(context);

        try {
            request.login(this.username, this.password);
        } catch (ServletException e) {
            context.addMessage(null, new FacesMessage("Login failed."));
            return "login";
        }
        return "index";
    }

    public void logout() {
        FacesContext context = getContext();
        HttpServletRequest request = getRequest(context);
        try {
            request.logout();
        } catch (ServletException e) {
            context.addMessage(null, new FacesMessage("Logout failed."));
        }
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRemoteUser() {
        HttpServletRequest request = getRequest(getContext());
        return request.getRemoteUser();
    }

    public boolean isLoggedIn() {
        HttpServletRequest request = getRequest(getContext());
        return (request.getRemoteUser() != null);
    }

    private HttpServletRequest getRequest(FacesContext context) {
        HttpServletRequest request
                = (HttpServletRequest) context.getExternalContext().getRequest();
        return request;
    }

    private FacesContext getContext() {
        FacesContext context = FacesContext.getCurrentInstance();
        return context;
    }
}

src/main/webapp/m/workorder/List.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<f:view  xmlns="http://www.w3.org/1999/xhtml"
         xmlns:p="http://primefaces.org/ui"
         xmlns:pm="http://primefaces.org/mobile"
         xmlns:ui="http://java.sun.com/jsf/facelets"
         xmlns:h="http://java.sun.com/jsf/html"
         xmlns:f="http://java.sun.com/jsf/core"
         xmlns:c="http://java.sun.com/jsp/jstl/core"
         contentType="text/html"
         renderKitId="PRIMEFACES_MOBILE"
         >
        #{workorderController.recreateModel()}
    <pm:page title="workorder list">
        <pm:view id="List">
            <pm:header title="#{bundle.ListWorkorderTitle}">
                <f:facet name="left">
                    <p:button value="Back" icon="back" href="/faces/m/index.xhtml"/>
                </f:facet>
                <f:facet name="right">
                    <p:button value="Settings" icon="gear" href="#settings"/>
                </f:facet>
            </pm:header>
            <pm:content>
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListWorkorderEmpty}" rendered="#{workorderController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{workorderController.items.rowCount > 0}">
                    <h:outputText value="#{workorderController.pagination.pageFirstItem + 1}..#{workorderController.pagination.pageLastItem + 1}/#{workorderController.pagination.itemsCount}"/>&nbsp;
                    <p:dataList value="#{workorderController.items}" var="item" type="inset" >
                        <h:outputLink value="#workorder#{item.id}?transition=slidefade">
                            <p>
                                <h:outputText value="#{bundle.ListWorkorderTitle_von}: " style="font-weight: bold;"/>
                                <h:outputText value="#{item.von}"/>
                                <h:outputText value="&nbsp;"/>

                                <h:outputText value="#{bundle.ListWorkorderTitle_ueber}: " style="font-weight: bold;"/>
                                <h:outputText value="#{item.ueber}"/>
                                <h:outputText value="&nbsp;"/>

                                <h:outputText value="#{bundle.ListWorkorderTitle_nach}: " style="font-weight: bold;"/>
                                <h:outputText value="#{item.nach}"/>
                            </p>
                            <p>
                                <h:outputText value="#{bundle.ListWorkorderTitle_uhr}: " style="font-weight: bold;"/>
                                <h:outputText value="#{item.uhr}"/>
                                <h:outputText value="&nbsp;"/>

                                <h:outputText value="#{bundle.ListWorkorderTitle_fahrernr}: " style="font-weight: bold;"/>
                                <h:outputText value="#{item.fahrernr}"/>
                                <h:outputText value="&nbsp;"/>
                                <h:outputText value="&nbsp;"/>
                                <h:outputText value="&nbsp;"/>
                            </p>
                        </h:outputLink>
                    </p:dataList>
                    <h:form>
                        <pm:buttonGroup
                            orientation="horizontal"
                            rendered="#{workorderController.pagination.itemsCount > workorderController.pagination.pageSize}">
                            <h:commandButton
                                action="#{workorderController.previous}"
                                value="#{bundle.Previous} #{workorderController.pagination.pageSize}"
                                rendered="#{workorderController.pagination.hasPreviousPage}"/>
                            <h:commandButton
                                action="#{workorderController.next}"
                                value="#{bundle.Next} #{workorderController.pagination.pageSize}"
                                rendered="#{workorderController.pagination.hasNextPage}"/>
                        </pm:buttonGroup>
                    </h:form>
                </h:panelGroup>
            </pm:content>
            <pm:footer>
                ${version.version} - ${version.timestamp}
            </pm:footer>
        </pm:view>

        <c:forEach items="#{workorderController.itemsAsList}" var="item" >
            <pm:view id="workorder#{item.id}">
                <pm:header title="Tour #{item.id}">
                    <f:facet name="left">
                        <p:button value="Back" icon="back" href="#List"/>
                    </f:facet>
                    <f:facet name="right">
                        <p:button value="Settings" icon="gear" href="#settings"/>
                    </f:facet>
                </pm:header>
                <pm:content>
                    <p:panelGrid columns="2" >
                        <h:outputText value="#{bundle.ViewWorkorderLabel_id}"/>
                        <h:outputText value="#{item.id}" title="#{bundle.ViewWorkorderTitle_id}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_dat}"/>
                        <h:outputText value="#{item.dat}" title="#{bundle.ViewWorkorderTitle_dat}">
                            <f:convertNumber pattern="#00" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_uhr}"/>
                        <h:outputText value="#{item.uhr}" title="#{bundle.ViewWorkorderTitle_uhr}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_von}"/>
                        <h:outputText value="#{item.von}" title="#{bundle.ViewWorkorderTitle_von}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_ueber}"/>
                        <h:outputText value="#{item.ueber}" title="#{bundle.ViewWorkorderTitle_ueber}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_nach}"/>
                        <h:outputText value="#{item.nach}" title="#{bundle.ViewWorkorderTitle_nach}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_job}"/>
                        <h:outputText value="#{item.job}" title="#{bundle.ViewWorkorderTitle_job}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_fahrschecknr}"/>
                        <h:outputText value="#{item.fahrschecknr}" title="#{bundle.ViewWorkorderTitle_fahrschecknr}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_preis}"/>
                        <h:outputText value="#{item.preis}" title="#{bundle.ViewWorkorderTitle_preis}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_fahrernr}"/>
                        <h:outputText value="#{item.fahrernr}" title="#{bundle.ViewWorkorderTitle_fahrernr}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_typ}"/>
                        <h:outputText value="#{item.typ}" title="#{bundle.ViewWorkorderTitle_typ}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_preischeck}"/>
                        <h:outputText value="#{item.preischeck}" title="#{bundle.ViewWorkorderTitle_preischeck}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_fahrscheckcheck}"/>
                        <h:outputText value="#{item.fahrscheckcheck}" title="#{bundle.ViewWorkorderTitle_fahrscheckcheck}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_sonderkonditionen}"/>
                        <h:outputText value="#{item.sonderkonditionen}" title="#{bundle.ViewWorkorderTitle_sonderkonditionen}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_summe}"/>
                        <h:outputText value="#{item.summe}" title="#{bundle.ViewWorkorderTitle_summe}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_kuerzel}"/>
                        <h:outputText value="#{item.kuerzel}" title="#{bundle.ViewWorkorderTitle_kuerzel}"/>
                        <h:outputText value="#{bundle.ViewWorkorderLabel_firmierung1}"/>
                        <h:outputText value="#{item.firmierung1}" title="#{bundle.ViewWorkorderTitle_firmierung1}"/>
                    </p:panelGrid>
                </pm:content>
                <pm:footer>
                    ${version.version}<br/>
                    ${version.timestamp}
                </pm:footer>
            </pm:view>
        </c:forEach>

        <pm:view id="settings">
            <pm:header title="Settings">
                <f:facet name="left">
                    <p:button value="Back" icon="back" href="#List"/>
                </f:facet>
            </pm:header>
            <pm:content>
                <h:outputText value="#{loginBean.remoteUser}"/>
                <br />
                <p:button outcome="/logout" value="log out" rendered="#{loginBean.loggedIn}" />
            </pm:content>
            <pm:footer>
                ${version.version} - ${version.timestamp}
            </pm:footer>
        </pm:view>

    </pm:page>
</f:view>